name: Snowflake CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Snowflake CLI
      uses: snowflakedb/snowflake-action-setup-cli@v1
      with:
        snowsql_version: 'latest'

    - name: Deploy to Snowflake
      run: |
        snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                -u ${{ secrets.SNOWFLAKE_USER }} \
                -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
                -r ${{ secrets.SNOWFLAKE_ROLE }} \
                -d ${{ secrets.SNOWFLAKE_DATABASE }} \
                -s ${{ secrets.SNOWFLAKE_SCHEMA }} \
                -f snowflake-ddl/stored-procedure/snow_script.sql
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
